### ISSUE TITLE
Request for test-set label on two task

### ISSUE THREAD

**Issue by Zyq-scut** [XiaoxiWei/NeurIPS_BEETL#4]
Hello, I am so interesting on this competition but it is too late for me to participate in. I want to do some research on this two dataset but test-set labels are unavailable.
Will you open the label for the test-set on two tasks to the public? Or can you send the test-set label to me? 
Look forward to your reply. Thanks in advance.

**Comment by XiaoxiWei** [comment]
Many thanks for your attention. We will publish the data on the MOABB website soon. Just like other data sets used in the Competition. Currently, you could pretest your methods on the 'leaderboard phase 1' data, that leaderboard is still open for submission and scoring.
Best,
Xiaoxi

**Comment by Zyq-scut** [comment]
> 
Thank you for your reply. I am unable to submit results on codalab as my participation has not been approved. What should I do for this?

**Comment by XiaoxiWei** [comment]
I approved it, enjoy your exploreation.

**Comment by Zyq-scut** [comment]
Thanks!
